code/testgame/testgame/urls.py
#coding:utf8
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'testgame.views.home', name='home'),
    # url(r'^testgame/', include('testgame.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^index/$','app_a.views.index'),
    url(r'^index1/$','app_a.views.index1'),
    url(r'^index2/$','app_a.views.index2'),
    url(r'^logout/$','app_a.views.mylogout'),

    url(r'^exam_a/$','app_a.views.exam_a'),  #常识测试
    url(r'^exam_a_info/(?P<eid>\d+)/$','app_a.views.exam_a_info'),
    url(r'^fa_wei/$','app_b.views.fa_wei'),

    url(r'^exam_b/$','app_b.views.exam_b'),  #常识测试
    url(r'^exam_b_info/(?P<eid>\d+)/$','app_b.views.exam_b_info'),
    
    url(r'^exam_c/$','app_c.views.exam_c'), #星座测试
    url(r'^exam_c_info/(?P<eid>\d+)/$','app_c.views.exam_c_info'),

    url(r'^exam_e/$','app_e.views.exam_e'), #输入年月日测试
    url(r'^exam_e_info/(?P<eid>\d+)/$','app_e.views.exam_e_info'),

   
)

code/testgame/app_a/models.py
#coding:utf8
from django.db import models

'''常识测试'''
class Exam_a(models.Model):
    exam_topic = models.CharField(max_length=200) #测试游戏名字
    exam_descript = models.TextField()   #测试游戏描述
    exam_photo = models.FileField(upload_to='./exam_a_photo') #测试游戏照片
    exam_picture = models.FileField(upload_to='./exam_a_picture') #测试游戏图片
   
    def __unicode__(self):
    	return self.exam_topic

'''题目选项'''
class Exam_a_question(models.Model):
    question_topic = models.CharField(max_length=200)  #具体题目名
    a = models.CharField(max_length=200) #题目选项
    b = models.CharField(max_length=200) 
    c = models.CharField(max_length=200) 
    answer = models.CharField(max_length=2)    #题目答案

    exam_a = models.ForeignKey(Exam_a)    #测试游戏外键

    def __unicode__(self):
    	return self.question_topic


'''返回结果'''
class Exam_option(models.Model):
    option_photo = models.FileField(upload_to='./option_a_photo')
    option_topic = models.CharField(max_length=200) #结果奖项名
    option_descript = models.TextField()    #结果描述
    score_min = models.IntegerField()  #游戏分数段最小值
    score_max = models.IntegerField()  #游戏分数段最大值
    #score = models.IntegerField(default=0)  #游戏所得分数    

    exam_a = models.ForeignKey(Exam_a)  #测试游戏外键

    def __unicode__(self):
    	return self.option_topic	

code/testgame/app_a/views.py
#encoding:utf8
from django.utils import simplejson as json
from app_a.models import *
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from weibo import APIClient, APIError
import weibo
import os
import sys
import webbrowser


APP_KEY = '3469247574'
APP_SECRET = 'd57bddcba8867095446ae0477b512cf6'
CALLBACK_URL = 'http://www.cenimei.com/index2'
client = weibo.APIClient(app_key=APP_KEY,app_secret=APP_SECRET,redirect_uri=CALLBACK_URL)

def index1(request):
    url = client.get_authorize_url()
    return render_to_response('index1.html',{'url':url})

def index2(request):
    code =request.GET.get('code')
    r = client.request_access_token(code)
    access_token = r.access_token
    espires_in = r.expires_in
    client.set_access_token(access_token,espires_in)
    request.session['token'] = access_token
    request.session['espires'] = espires_in
    print '====',request.session.get('k')
    uid = client.account.get_uid.get()
    id = uid['uid']  
    username = id
    email = str(id) + '@qq.com'
    password = id
    user = authenticate(username=id,password=id)
    if user is None:
        User.objects.create_user(username,email,password)
    #把用户存到django的用户中，并完成django用户登录
    #username = '按照规则生成用户名  uid'
    #user = User(username,)
    return HttpResponseRedirect('/index/')

import random
def index(request):
    access_token = request.session['token'] 
    espires_in = request.session['espires']
    client.set_access_token(access_token,espires_in)
    #print '*****',request.session.get('k')
    uid = client.account.get_uid.get()
    id = uid['uid']
    ur = client.users.show.get(uid=id)
    name = ur['name']
    headimg = ur['avatar_large']
    request.session['userinfo'] = {'name':name,'headimg':headimg}
    exams_a = Exam_a.objects.all()
    
    friends = client.friendships.friends.bilateral.ids.get(uid=id)
    #print friends
    ids = friends['ids']  
    
    #print ids   
    fr = []  
    for id1 in ids[0:5]:
       # print '======',id1
        try:
            fr.append(client.users.show.get(uid=id1))
        except APIError:
            pass
    request.session['fr'] = fr    	
    headimgs = [] 
    names = []   
    for fr1 in fr:
        headimgs.append(fr1['avatar_large'])
        #print '$$$$$$',headimgs
        names.append(fr1['name'])
        #print '######',names
    #print headimgs

    #print "************************",friends     
    request.session['headimg'] = headimgs
    request.session['name'] = names   	
   # exams_b = Exam_b.objects.all()
 #   exams_c = Exam_c.objects.all()
   # exams_d = Exam_d.objects.all()
  #  exams_e = Exam_e.objects.all()
    return render_to_response('index.html',locals())



def mylogout(request):
    request.session.get('k')
    client.account.end_session 
    logout(request)
    return HttpResponseRedirect('/index1')


'''常识测试主页'''
def exam_a(request):
    request.session.get('k')
    uid = client.account.get_uid.get()
    id = uid['uid']
    ur = client.users.show.get(uid=id)
    name = ur['name']
    #email = client.account.profile.email.get()
    #eml = email['email']
    headimg = ur['avatar_large']
    exams = Exam_a.objects.all()
    return render_to_response('exam_a.html',locals())

'''具体测试页面'''
import os
def exam_a_info(request,eid):
    request.session.get('k')
    uid = client.account.get_uid.get()
    id = uid['uid']
    ur = client.users.show.get(uid=id)
    name = ur['name']
    #email = client.account.profile.email.get()
    #eml = email['email']
    headimg = ur['avatar_large']
    exam = Exam_a.objects.get(id=eid)
    questions = exam.exam_a_question_set.all()
    options = exam.exam_option_set.all()
    questions_list=[]
    for question in questions:
        questions_list.append({
            'id':question.id - (int(eid)-1)*5, 
            'question_topic':question.question_topic,
            'a':question.a,
            'b':question.b,
            'c':question.c,
            'answer':question.answer,
            'ans':'' 
})    
    quest = json.dumps(questions_list)
    options_list=[]
    for option in options:
        photo_name = os.path.basename(option.option_photo.name)
        photo_name = os.path.join('static', 'option_a_photo', photo_name)
        print photo_name
        options_list.append({
            'option_photo':photo_name,
            'id':option.id,
            'option_topic':option.option_topic,
            'option_descript':option.option_descript,
            'score_min':option.score_min,
            'score_max':option.score_max
})
    opt = json.dumps(options_list)
    return render_to_response('exam_a_info.html',locals())

code/testgame/app_a/templates/exam_a.html
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title></title>
	<style>

	
	
	</style>
</head>
<body>
{% extends 'index.html'%}
{% block content %}
<div class="row" style="margin-left:220px;">
<div class="span2"><img src="/static/images/logo2.jpg" alt=""  width="150px" height="150px" class="img-polaroid"></div>
<div class="span5" style="margin-top:90px;margin-left:-10px" ><h2>开心萌妹子 "测" &nbsp;"测" &nbsp;"测" </h2></div>
</div>
<hr / >

<div class="row" style="margin-left:180px">

{%for exam in exams%}

<a href="/exam_a_info/{{exam.id}}" ><div class="span3" style="border:1px solid white;width:230px;height:230px;margin-top:10px;margin-left:50px;">
		<div style="width:180px;"><img src="/static/{{exam.exam_photo}}" alt="" width="180px" style="margin-top:10px;margin-left:20px;" /></div>
		<h5 style="margin-left:50px;">{{exam.exam_topic}}</h5>
</div></a>
{%endfor%}
</div>

<div class="modal" id="myModal">
                     <div class="modal-header">
                        <a class="close" data-dismiss="modal">×</a>
                        <h3>测你妹啊来历</h3>
                      </div>
                    <div class="modal-body">
                    <p>这是一个测试游戏的平台，由于你妹一词的影响而取此名,此应用由CNM_CREW开发制作，这只是我们的第一个版本，今后还会不断更新。CNM_CREW初来乍到，希望前辈们，用户们多多支持，有什么好的建议可以联系我们，再次谢谢大家，祝大家天天开心。</p>
                    </div>
                   <div class="modal-footer">
                    <p>谢谢您的支持</p>
                   </div>
                </div>

<script src="/static/js/jquery-1.9.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript">
$('#myModal').modal({
    backdrop:true,
    keyboard:false,
    show:true
    });
$('#myModal').modal('show')
$('#myModal').modal('hide')
</script>

{% endblock %}
</body>
</html>

code/testgame/app_a/templates/exam_a_info.html
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title></title>
	<link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<style>
	#main{
	width: 800px;
	margin: 0 auto;
	border:0px blank solid;	
	}	
	div.none {
           	list-style-type: none;
            font-size: 20px;	
	         margin-top: 50px;
	         margin-left: 100px;
	         
	}	
	#question_topic{
           font-size: 25px;
            margin-top: 50px;
            margin-left: 100px;	
	}
	#question_id{
	    margin-top: 10px;
       margin-left: -60px;
       font-size: 30px;
       color: #9932cc;  	
	}
	#total{
	    margin-top: 20px;
       margin-left: -60px;
       font-size: 30px;
       color:  #9932cc;	
	}
	</style>
</head>
<body>
{% extends 'index.html'%}
{% block content %}

<img src="/static/{{exam.exam_picture}}" width="55%"   class="img-polaroid" style="height:200px;margin-left:300px"><br />
<div id="main" style="margin-left:355px">
<div id="question_id"></div>
<div id="total"></div>
<div id="question_topic"></div>
<div class="none">
        <li style="background-color:pink;width:400px;height:30px;"><input type="radio" name="ans" value="a" id="id_a">A.<span id="a"></span></li><br /><br />  
        <li style="background-color:pink;width:400px;height:30px;"><input type="radio" name="ans" value="b" id="id_b" />B.<span id="b"></span></li><br /><br /> 
        <li style="background-color:pink;width:400px;height:30px;"><input type="radio" name="ans" value="c" id="id_c" />C.<span id="c"></span></li>
               
</div>

<div class="modal" id="myModal1">
                     <div class="modal-header">
                        <a class="close" data-dismiss="modal">×</a>
                        <h3 id="fenshu"></h3>
                        <h3 id="rank"></h3>
                         <img src='' id="img1" />
                      </div>
                   <div class="modal-body">
                    
                   
                    <p id="descript"></p>
                    </div>
                   <div class="modal-footer">
                    <p>谢谢您的支持</p>
                   </div>
                </div>   
                
<div class="modal" id="myModal">
                     <div class="modal-header">
                        <a class="close" data-dismiss="modal">×</a>
                        <h3>测你妹啊来历</h3>
                      </div>
                    <div class="modal-body">
                    <p>这是一个测试游戏的平台，由于你妹一词的影响而取此名</p>
                    </div>
                   <div class="modal-footer">
                    <p>谢谢您的支持</p>
                   </div>
                </div>              
                
  
<script type="text/javascript" >
quest = eval('('+"{{quest|escapejs}}"+')')
opt = eval('('+"{{opt|escapejs}}"+')')


var question_topic = document.getElementById('question_topic')
var a = document.getElementById('a')
var b = document.getElementById('b')
var c = document.getElementById('c')
var ans = document.getElementsByName('ans');
var question_id = document.getElementById('question_id')
document.getElementById('total').innerHTML = '共' + quest.length  +  '题'

var qid = 0;
var n = 0;
document.getElementById('id_a').onclick=next;
document.getElementById('id_b').onclick=next;
document.getElementById('id_c').onclick=next;


//保存用户选的选项
function saveAns(){
 for(var i=0;i<ans.length;i++){
  if(ans[i].checked){
quest[qid].ans = ans[i].value;
//alert(quest[qid].ans)
}
}
}
//翻页
fenshu = document.getElementById('fenshu')
function next(){
saveAns();
qid++;

if(qid > quest.length - 1){
//qid = quest.length - 1

grade();
fenshu.innerHTML = '您的分数是：' + n;
ranks();
}

setVal();
}

//给题目赋值
function setVal(){
for(i=0;i<ans.length;i++){
ans[i].checked = false;
if(ans[i].value == quest[qid].ans){
ans[i].checked = true;
}
}
question_topic.innerHTML = quest[qid].question_topic;
a.innerHTML = quest[qid].a;
b.innerHTML = quest[qid].b;
c.innerHTML = quest[qid].c;
question_id.innerHTML = '第' + quest[qid].id + '题'
}

 
function grade(){
for(var i=0;i<quest.length;i++){
//alert(i);
answer = quest[i].answer;
//alert(answer);
//alert(quest[i].ans)
if(answer == quest[i].ans){
n += 20;
};
};
}
grade();
setVal();

function ranks(){
for(i=0;i<opt.length;i++){
if(opt[i].score_min <= n && n<=opt[i].score_max){
    document.getElementById('rank').innerHTML = opt[i].option_topic;
    document.getElementById('descript').innerHTML = opt[i].option_descript; 
    document.getElementById('img1').src = opt[i].option_photo; 
    s =  document.getElementById('img1').src.substr(30);      
    //alert(s);
    document.getElementById('img1').src= s;
}
}
    $('#myModal1').modal('show');
}

</script>


<script src="/static/js/jquery-1.9.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript">
$('#myModal1').modal({
    backdrop:true,
    keyboard:false,
    show:true
    });
$('#myModal1').modal('hide')


$('#myModal').modal({
    backdrop:true,
    keyboard:false,
    show:true
    });
$('#myModal').modal('show')
$('#myModal').modal('hide')
</script>

</div>
{% endblock %}
</body>
</html>

code/testgame/app_a/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<link href="/static/css/lanrenzhijia.css" rel="stylesheet" type="text/css" />
<link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
<script type="text/javascript" src="/static/js/swfobject.js"></script>
<style>
body {
    background-color: #F5F5F5;
    color: #333333;}
.hero-unit{margin-top: 43px;padding: 1px;height: 50px}
.span4 input[type='text']
{
    font-size: 16px;
    height: auto;
    margin-bottom: 15px;
    padding: 7px 9px;
}

td button{
   margin-top: -20px;
}

.row-fluid .span6:hover{
    color: red;
}
.row-fluid .span3:hover{
    color: red;
}

</style>
</head>
<body>

    <!--<div class="progress">
    <div class="bar" style="width: 100%;"></div>
    </div>

    <div class="progress progress-striped active" style="width:500px">
    <div class="bar" style="width: 100%;"></div>
    </div>-->

<div class="navbar navbar-inverse navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button"></button>
         <a class="brand" href="/index">测你妹</a>
           <div class="nav-collapse collapse">
              <ul class="nav">
                  <li class="active"><a href="/index">主页</a></li>
                  <li><a  data-toggle="modal" href="#myModal" >关于我们</a></li>
                  <li><a data-toggle="modal" href="#myModal2" >联系我们</a></li>
                  <li style="margin-left:700px"><span style="color:yellow">{{name}}<span><img src="{{headimg}}" width="50px" height="30px"><a href="/logout" >注销</li>
              </ul>             
          </div>
     </div>
  </div>
</div>

<!--<div class="row-fluid" style="margin-top:100px">
  <div class="span2"></div>
  <div class="span8">   
    <div class="span2"style="margin-top:-20px"><h3><a href='/index'>测你妹啊</a></h3></div> 
    <div class="span2" style="font-size:20px"><a  href='/exam_a'>开心妹测试</a></div> 
    <div class="span2" style="font-size:20px"><a  href='#'>友趣妹测试</a></div> 
    <div class="span2" style="font-size:20px"><a  href='/exam_c'>星座妹测试</a></div> 
    <div class="span2" style="font-size:20px"><a  href='/exam_e'>趣味妹测试</a></div> 
  </div>
  </div>
  <div class="span2"></div>
</div>
-->

<a  href='/index' style="width:100px;"><img src="/static/images/logo.png" style="margin-top:70px;margin-left:430px"></a>
<div class="container" >
<div class="masthead" >
 <div class="navbar" >
   <div class="navbar-inner" >
     <div class="container" style="background-color:#00FFFF; ">
       <ul class="nav" style="margin-left:200px">
        
         <li><a  href='/exam_a'><h3>开心妹测试</h3></a></li>
         <li><a  href='/exam_b'><h3>友趣妹测试</h3></a></li>        
         <li><a  href='/exam_c'><h3>星座妹测试</h3></a></li>
         <li><a  href='/exam_e'><h3>趣味妹测试</h3></a></li>
       </ul>
     </div>
   </div>
 </div>
</div>
</div>

{% block content %}

</div>
<hr/>

<div class="modal" id="myModal">
                     <div class="modal-header">
                        <a class="close" data-dismiss="modal">×</a>
                        <h3>测你妹啊来历</h3>
                      </div>
                    <div class="modal-body">
                    <p>这是一个测试游戏的平台，由于你妹一词的影响而取此名,此应用由CNM_CREW开发制作，这只是我们的第一个版本，今后还会不断更新。CNM_CREW初来乍到，希望前辈们，用户们多多支持，有什么好的建议可以联系我们，再次谢谢大家，祝大家天天开心。</p>
                    </div>
                   <div class="modal-footer">
                    <p>谢谢您的支持</p>
                   </div>
                </div>

<div class="modal" id="myModal2">
                     <div class="modal-header">
                        <a class="close" data-dismiss="modal">×</a>
                        <h3>联系方式</h3>
                      </div>
                    <div class="modal-body">
                    <p>fengzizhang888@gmail.com</p>
                    <p>707137434@qq.com</p>
                    <p>641987841@qq.com</p>
                    </div>
                   <div class="modal-footer">
                    <p>谢谢您的支持</p>
                   </div>
                </div>

<script src="/static/js/jquery-1.9.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript">
	

$('#myModal').modal({
    backdrop:true,
    keyboard:false,
    show:true
    });
$('#myModal').modal('show')
$('#myModal').modal('hide')

$('#myModal2').modal({
    backdrop:true,
    keyboard:false,
    show:true
    });
$('#myModal2').modal('show')
$('#myModal2').modal('hide')
</script>


<!--

<div class="row" style="margin-left:180px">

{%for exam_a in exams_a%}

<a href="/exam_a_info/{{exam.id}}" ><div class="span3" style="border:1px solid white;width:230px;height:230px;margin-top:10px;margin-left:50px;">
		<div style="width:180px;"><img src="/static/{{exam_a.exam_photo}}" alt="" width="180px" style="margin-top:10px;margin-left:20px;" /></div>
		<h5 style="margin-left:50px;">{{exam_a.exam_topic}}</h5>
</div></a>



 <div class="gallery">
            <a id="1" draggable="true" href="/exam_a_info/{{exam_a.id}}" ><img src="/static/{{exam_a.exam_photo}}" ></a>


{%endfor%}
</div>
</div>
-->

 <div class="gallery">
            <a id="1" draggable="true" href="/exam_a_info/1"><img src="/static/images/dati.gif"></a>
            <a id="2" draggable="true" href="/exam_b_info/1"><img src="/static/images/zhiqingchun.jpg"></a>
            <a id="3" draggable="true" href="/exam_c_info/4"><img src="/static/images/dota.jpg"></a>
            <a id="4" draggable="true" href="/exam_a_info/2"><img src="/static/images/kengdie.jpg"></a>
            <a id="5" draggable="true" href="/exam_c_info/1"><img src="/static/images/zc7.jpg"></a>
            <a id="6" draggable="true" href="/exam_a_info/3"><img src="/static/images/guzhuang.jpg"></a>          
            <a id="7" draggable="true" href="/exam_e_info/2"><img src="/static/images/zc1.jpeg"></a>
             <a id="8" draggable="true" href="/exam_e_info/3"><img src="/static/images/zc3.jpg"></a>
            <a id="9" draggable="true" href="/exam_c_info/3"><img src="/static/images/zc10.jpg"></a>
            <a id="10" draggable="true" href="/exam_c_info/2"><img src="/static/images/zc6.jpg"></a>
            <a id="11" draggable="true" href="/exam_a_info/2"><img src="/static/images/kengdie.jpg"></a>
            <a id="12" draggable="true" href="/exam_e_info/1"><img src="/static/images/vnac53l0.gif"></a>
        </div>
        
        
        <script src="/static/js/lanrenzhijia.js"></script>
{% endblock %}
<div style="height:100px"></div>        
</body>
</html>

code/testgame/app_a/templates/index1.html
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<title></title>
<style>
body {
    background-color: #F5F5F5;
    color: #333333;}
</style>    	
</head>
<body>
<a href="{{url}}" >
<div style="margin-left:500px">
<img src="/static/images/logo3.jpeg" alt="" />
<div>
<div style="margin-left:80px"><h2>Join ME</h2></div></a>	
</body>
</html>